export const initialState = {
	cart: [],



	PRODUCTS: [
		{
			productId: 1,
			name: 'Chico',
    	slug: 'chico',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: 'CHICO PINERAS. I love it, this arrangement that we have with farmers where they would send us what the have growing on trees around their farms, around their houses. We are often surprised. If you’ve been going to RuRi West, you’ll notice that the number of exotic fruits and vegetables are increasing, Ganado ang farmers to forage for us, it’s extra income.\n So tonight we’ve just been contacted by a new farmer that he will be harvesting, get ready, Chico Pineras.\n “Chico Pineras refers to a prized, sweet variety of Sapodilla (Chico in Spanish/Filipino), a tropical fruit known for its rich, caramel-like flavor, smooth texture with slight grittiness, and brown skin, making it a popular, healthy snack or dessert ingredient, especially in the Philippines, where it’s cultivated for its excellent taste and consistent quality.” — Google\n CHICO PINERAS SNAP BUY. We are happy to offer our members a sweet variety of Chico. For your P299, you shall get 2 kilos.',
			isActive: true,
			variants: [
				{
					variantId: 'chico-default',
					label: 'Default',
					price: 299,
					stock: 23,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '2kg',
					},
				},
			],
		},
		{
			productId: 2,
			name: 'Magic Kamote',
    	slug: 'magic-kamote',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'magic-kamote-default',
					label: 'Default',
					price: 350,
					stock: 43,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '3kg',
					},
				},
			],
		},
		{
			productId: 3,
			name: 'Pineapples',
    	slug: 'pineapples',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'pineapples-default',
					label: 'Default',
					price: 250,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '3kg',
						amount: '1 piece',
					},
				},
			],
		},
		{
			productId: 4,
			name: 'Cauliflower',
    	slug: 'cauliflower',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'cauliflower-default',
					label: 'Default',
					price: 499,
					stock: 121,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 5,
			name: 'Lemons',
    	slug: 'lemons',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'lemons-default',
					label: 'Default',
					price: 399,
					stock: 0,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '4kg',
					},
				},
			],
		},
		{
			productId: 6,
			name: 'Earthworm Poop',
    	slug: 'earthworm-poop',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'earthworm-poop-default',
					label: 'Default',
					price: 199,
					stock: 35,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 7,
			name: 'Rescue Sampler',
    	slug: 'rescue-sampler',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'rescue-sampler-default',
					label: 'Default',
					price: 399,
					stock: 44,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 8,
			name: 'Thank-You Tankan',
    	slug: 'thank-you-tankan',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'thank-you-tankan-default',
					label: 'Default',
					price: 499,
        	unlimitedStock: false,
					stock: 0,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '3kg',
					},
				},
			],
		},
		{
			productId: 9,
			name: 'Golden Zucchini',
    	slug: 'golden-zucchini',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'golden-zucchini-default',
					label: 'Default',
					price: 599,
					stock: 0,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '2kg',
					},
				},
			],
		},
		{
			productId: 10,
			name: 'Katmon',
    	slug: 'katmon',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'katmon-default',
					label: 'Default',
					price: 249,
					stock: 23,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '2kg',
					},
				},
			],
		},
		{
			productId: 11,
			name: 'Christmas Bintong Basket',
    	slug: 'christmas-bintong-basket',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'christmas-bintong-basket-default',
					label: 'Default',
					price: 550,
					stock: 1,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '3kg',
					},
				},
			],
		},
		{
			productId: 12,
			name: 'Black Corn',
    	slug: 'black-corn',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'black-corn-default',
					label: 'Default',
					price: 499,
					stock: 0,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '3kg',
					},
				},
			],
		},
		{
			productId: 13,
			name: 'Brown Rice',
    	slug: 'brown-rice',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'brown-rice-default',
					label: 'Default',
					price: 549,
					stock: 17,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 14,
			name: 'Maningong Bayong',
    	slug: 'maningong-bayong',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'maningong-bayong-default',
					label: 'Default',
					price: 999,
					stock: 46,
        	unlimitedStock: false,
					ruriCoin: 2,
					imgPath: '',
					additionalInfo: {
						weight: '1kg',
					},
				},
			],
		},
		{
			productId: 15,
			name: 'Papaya',
    	slug: 'papaya',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'papaya-default',
					label: 'Default',
					price: 299,
					stock: 12,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 16,
			name: 'Masaganang Tampipi',
    	slug: 'masaganang-tampipi',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'masaganang-tampipi-default',
					label: 'Default',
					price: 1599,
					stock: 40,
        	unlimitedStock: false,
					ruriCoin: 3,
					imgPath: '',
				},
			],
		},
		{
			productId: 17,
			name: 'Green Cabbage',
    	slug: 'green-cabbage',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'green-cabbage-default',
					label: 'Default',
					price: 249,
					stock: 0,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 18,
			name: 'Bayanihang Ani',
    	slug: 'bayanihang-ani',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'bayanihang-ani-default',
					label: 'Default',
					price: 499,
					stock: 20,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 19,
			name: 'Wombok',
    	slug: 'wombok',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'wombok-default',
					label: 'Default',
					price: 249,
					stock: 0,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 20,
			name: 'Meruri Christmas',
    	slug: 'meruri-christmas',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'meruri-christmas-default',
					label: 'Default',
					price: 1299,
					stock: 58,
        	unlimitedStock: false,
					ruriCoin: 3,
					imgPath: '',
					additionalInfo: {
						weight: '1kg',
					},
				},
			],
		},
		{
			productId: 21,
			name: 'Saba Banana',
    	slug: 'saba-banana',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'saba-banana-default',
					label: 'Default',
					price: 399,
					stock: 35,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '10kg',
					},
				},
			],
		},
		{
			productId: 22,
			name: 'Chewy Ube Jam',
    	slug: 'chewy-ube-jam',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'chewy-ube-jam-default',
					label: 'Default',
					price: 999,
					stock: 24,
        	unlimitedStock: false,
					ruriCoin: 2,
					imgPath: '',
					additionalInfo: {
						weight: '3kg',
					},
				},
			],
		},
		{
			productId: 23,
			name: 'Carrots',
    	slug: 'carrots',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'carrots-default',
					label: 'Default',
					price: 199,
					stock: 25,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '4kg',
					},
				},
			],
		},
		{
			productId: 24,
			name: 'White Rice',
    	slug: 'white-rice',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'white-rice-default',
					label: 'Default',
					price: 300,
					stock: 8,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 25,
			name: 'Lakan Corn',
    	slug: 'lakan-corn',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'lakan-corn-default',
					label: 'Default',
					price: 299,
					stock: 0,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '4kg',
					},
				},
			],
		},
		{
			productId: 26,
			name: 'Adlai',
    	slug: 'adlai',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'adlai-default',
					label: 'Default',
					price: 499,
					stock: 17,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '1kg',
					},
				},
			],
		},
		{
			productId: 27,
			name: 'Zapote',
    	slug: 'zapote',
			category: 'Rescue Buy',
			categorySlug: 'rescue-buy',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'zapote-default',
					label: 'Default',
					price: 499,
					stock: 0,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '4kg',
					},
				},
			],
		},
		{
			productId: 28,
			name: 'Probiotic Eggs Tray',
    	slug: 'probiotic-eggs-tray',
			category: 'Ruri Exclusives',
			categorySlug: 'ruri-exclusives',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'probiotic-eggs-tray-default',
					label: 'Default',
					price: 370,
					stock: 28,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '1kg',
						quantity: '1 dozen, 1 tray'
					},
				},
			],
		},
		{
			productId: 29,
			name: 'Ruri Eggs Dozen',
    	slug: 'ruri-eggs-dozen',
			category: 'Ruri Exclusives',
			categorySlug: 'ruri-exclusives',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'ruri-eggs-dozen-default',
					label: 'Default',
					price: 370,
					stock: 1,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '1kg',
						quantity: '1 dozen, 1 tray'
					},
				},
			],
		},
		{
			productId: 30,
			name: 'Ruri Eggs Tray',
    	slug: 'ruri-eggs-tray',
			category: 'Ruri Exclusives',
			categorySlug: 'ruri-exclusives',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'ruri-eggs-tray-default',
					label: 'Default',
					price: 900,
					stock: 0,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '1kg',
						quantity: '1 dozen, 1 tray'
					},
				},
			],
		},
		{
			productId: 31,
			name: 'Probiotic Eggs Dozen',
    	slug: 'probiotic-eggs-dozen',
			category: 'Ruri Exclusives',
			categorySlug: 'ruri-exclusives',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'probiotic-eggs-dozen-default',
					label: 'Default',
					price: 180,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 0,
					imgPath: '',
					additionalInfo: {
						weight: '1kg',
						quantity: '1 dozen, 1 tray'
					},
				},
			],
		},
		{
			productId: 32,
			name: 'Maningong Bayong',
    	slug: 'maningong-bayong',
			category: 'Ruri Exclusives',
			categorySlug: 'ruri-exclusives',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: '-bayong-default',
					label: 'Default',
					price: 999,
					stock: 45,
        	unlimitedStock: false,
					ruriCoin: 2,
					imgPath: '',
					additionalInfo: {
						weight: '1kg',
					},
				},
			],
		},
		{
			productId: 33,
			name: 'Masaganang Tampipi',
    	slug: 'masaganang-tampipi',
			category: 'Ruri Exclusives',
			categorySlug: 'ruri-exclusives',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'masaganang-tampipi-default',
					label: 'Default',
					price: 1599,
					stock: 40,
        	unlimitedStock: false,
					ruriCoin: 3,
					imgPath: '',
				},
			],
		},
		{
			productId: 34,
			name: 'Bayanihang Ani',
    	slug: 'bayanihang-ani',
			category: 'Ruri Exclusives',
			categorySlug: 'ruri-exclusives',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'bayanihang-ani-default',
					label: 'Default',
					price: 499,
					stock: 19,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 35,
			name: 'Meruri Christmas',
    	slug: 'meruri-christmas',
			category: 'Ruri Exclusives',
			categorySlug: 'ruri-exclusives',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: '-default',
					label: 'Default',
					price: 1299,
					stock: 58,
        	unlimitedStock: false,
					ruriCoin: 3,
					imgPath: '',
					additionalInfo: {
						weight: '3kg',
					},
				},
			],
		},
		{
			productId: 36,
			name: 'San Jacinto Tablea',
    	slug: 'san-tacinto-tablea',
			category: 'Ruri Exclusives',
			categorySlug: 'ruri-exclusives',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'san-tacinto-tablea-default',
					label: 'Default',
					price: 499,
					stock: 0,
        	unlimitedStock: false,
					ruriCoin: 1,
					imgPath: '',
					additionalInfo: {
						weight: '0.5kg',
					},
				},
			],
		},
		{
			productId: 37,
			name: 'Probiotic Eggs Wholesale',
    	slug: 'probiotic-eggs-wholesale',
			category: 'Ruri Exclusives',
			categorySlug: 'ruri-exclusives',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'probiotic-eggs-wholesale-default',
					label: 'Default',
					price: 1799,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 4,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
					},
				},
			],
		},
		{
			productId: 38,
			name: 'Heritage Harvest Box',
    	slug: 'heritage-harvest-box',
			category: 'CSA Boxes',
			categorySlug: 'csa-boxes',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'heritage-harvest-box-default',
					label: 'Default',
					price: 1699,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 3,
					imgPath: '',
					additionalInfo: {
						weight: '7-10kg',
						size: 'Biyayang Bayan Mini, Biyayang Bayan Grande',
					},
				},
			],
		},
		{
			productId: 39,
			name: 'Superfood Box',
    	slug: 'superfood-box',
			category: 'CSA Boxes',
			categorySlug: 'csa-boxes',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'superfood-box-default',
					label: 'Default',
					price: 799,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 2,
					imgPath: '',
					additionalInfo: {
						weight: '5kg',
						cycle: 'On-Demand, Weekly'
					},
				},
			],
		},
		{
			productId: 40,
			name: 'Get-Well-Soon Box',
    	slug: 'get-well-soon-box',
			category: 'CSA Boxes',
			categorySlug: 'csa-boxes',
			description: '',
			isActive: true,
			variants: [
				{
					variantId: 'get-well-soon-box-default',
					label: 'Default',
					price: 1199,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 2,
					imgPath: '',
				},
			],
		},
		{
			productId: 41,
			name: 'Furry Friends Box',
    	slug: 'furry-friends-box',
			category: 'CSA Boxes',
			categorySlug: 'csa-boxes',
			description: '',
			isActive: true,
			variants: [
				{
      		variantId: 'ffb-daily-bowl',
					label: 'Daily Bowl',
					price: 799,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 2,
					imgPath: '',
					additionalInfo: {
						weight: '10kg',
					},
				},
				{
      		variantId: 'ffb-shelter-pack',
					label: 'Shelter Pack',
					price: 1999,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 4,
					imgPath: '',
					additionalInfo: {
						weight: '30kg',
					},
				},
			]
		},
		{
			productId: 42,
			name: 'Sunrise Harvest Box',
    	slug: 'sunrise-harvest-box',
			category: 'CSA Boxes',
			categorySlug: 'csa-boxes',
			description: '',
			isActive: true,
			variants: [
				{
      		variantId: 'ffb-on-demand',
					label: 'On-Demand',
					price: 1599,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 3,
					imgPath: '',
					additionalInfo: {
						weight: '10kg',
					},
				},
				{
      		variantId: 'ffb-bi-weekly',
					label: 'Bi-weekly',
					price: 2798,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 6,
					imgPath: '',
					additionalInfo: {
						weight: '10kg',
					},
				},
				{
      		variantId: 'ffb-weekly',
					label: 'Weekly',
					price: 4796,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 10,
					imgPath: '',
					additionalInfo: {
						weight: '10kg',
					},
				},
			]
		},
		{
			productId: 43,
			name: 'Family Essentials Box',
    	slug: 'family-essentials-wox',
			category: 'CSA Boxes',
			categorySlug: 'csa-boxes',
			description: '',
			isActive: true,
			variants: [
				{
      		variantId: 'ffb-on-demand',
					label: 'On-Demand',
					price: 1799,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 4,
					imgPath: '',
					additionalInfo: {
						weight: '15kg',
					},
				},
				{
      		variantId: 'ffb-bi-weekly',
					label: 'Bi-weekly',
					price: 3198,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 6,
					imgPath: '',
					additionalInfo: {
						weight: '30kg',
					},
				},
				{
      		variantId: 'ffb-weekly',
					label: 'Weekly',
					price: 5596,
					stock: 3,
        	unlimitedStock: false,
					ruriCoin: 11,
					imgPath: '',
					additionalInfo: {
						weight: '60kg',
					},
				},
			]
		},
	],
	CATEGORIES: [
		{
			categoryId: 1,
			name: 'CSA Boxes',
			imgPath: '',
		},
		{
			categoryId: 2,
			name: 'Fruits',
			imgPath: '',
		},
		{
			categoryId: 3,
			name: 'Rescue Buy',
			imgPath: '',
		},
		{
			categoryId: 4,
			name: 'Ruri Exclusives',
			imgPath: '',
		},
		{
			categoryId: 5,
			name: 'Wholesale Products',
			imgPath: '',
		},
	],
}